# Generated by Django 6.0.3 on 2026-03-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
