# Generated by Django 6.0.3 on 2026-03-26 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_account_balance_alter_transaction_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after_to_user',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='After a transfer: receiver balance (null for deposit/withdrawal).', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, help_text="After a transfer: sender balance. After deposit/withdrawal: that party's balance.", max_digits=12, null=True),
        ),
    ]
