"""
Pydantic models that validate that the data is correct and consistent.
This module contains the following models:
- UserBase
- UserCreate
- User
- UserInDB
- TransactionBase
- TransactionCreate
- Transaction
It prevenst data corruption and ensures that the data is consistent and valid.
"""


from datetime import datetime
from typing import Literal

from pydantic import BaseModel, EmailStr, Field


class UserBase(BaseModel):
    """Base fields for a user, shared between creation and reading."""
    username: str = Field(..., min_length=3, max_length=20, pattern="^[a-zA-Z0-9_]+$")
    email: EmailStr
    full_name: str | None = None

class UserCreate(UserBase):
    """Model for registering new users (includes password)."""
    password: str = Field(..., min_length=6)

class User(UserBase):
    """Complete user model as it lives in the system."""
    id: int | None = Field(None, description="Unique identifier generated by the database")
    balance: float = Field(default=0.0, ge=0)
    # password is not included here for security when returning data

class UserInDB(User):
    """User model as stored in the database (includes hashed password)."""
    password: str

class TransactionBase(BaseModel):
    """Base structure of a transaction."""
    amount: float = Field(..., gt=0)
    description: str | None = Field(None, max_length=100)
    type: Literal["deposit", "transfer_in", "transfer_out"]

class TransactionCreate(TransactionBase):
    """Data needed to create a transaction."""
    owner: str
    from_user: str
    to_user: str

class Transaction(TransactionCreate):
    """Complete transaction with system-generated metadata.
    If a date is not provided, the system will generate the current date and time."""
    date: datetime = Field(default_factory=datetime.now)
    balance: float

    model_config = {
        "extra": "forbid"  # Forbidden extra fields
    }
